### ISSUE TITLE
IE11 crash

### ISSUE THREAD

**Issue by giregk** [convertigo/c8osdk-js#3]
When using full sync, the application crashes on IE11

![image](https://user-images.githubusercontent.com/20740580/42223436-082f83fe-7ed8-11e8-8b05-20331e547f0b.png)

There are a lot of discussions about IE11 not supporting pouchDB local databases on the internet. Apparently a race condition. Indeed, I managed to not have this error from time to time when refreshing the page.

**Comment by CharlesGrimont** [comment]
Can you provide me a test case, or explain me how to reproduce this ?

**Comment by CharlesGrimont** [comment]
Closed due to inactivity
